# Generated by Django 5.0.4 on 2024-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_post_parent_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_posts',
            field=models.ManyToManyField(blank=True, related_name='parent_post', to='sim.post'),
        ),
    ]
