# Generated by Django 5.0.4 on 2024-05-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_customuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('correct_answer_index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_videos', to='sim.class')),
                ('video_questions', models.ManyToManyField(blank=True, related_name='videos', to='sim.videoquestion')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='classes', to='sim.video'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
